datasynctool: Handle when no paths are watching
Currently, datasynctool -w reports a JSON format error when data-sync
is not watching any paths. In this case, the watching_paths field is
null, whereas it contains an array of strings when paths are being
watched.

Treat null as a valid value and print a meaningful message when no paths
are being watched instead of reporting a JSON parsing error.

The error observed :

```
root@rbmc-prototype:~# datasynctool -w
Error: Unexpected JSON format in watching paths file
root@rbmc-prototype:~# cat /tmp/data_sync_watching_paths.json
{
    "timestamp": "2026-08-20T09:47:42Z",
    "watching_paths": null
}root@rbmc-prototype:~#
```

Tested :

After fix :

```
[root@rbmc (1:active)] ~ # cat /tmp/data_sync_watching_paths.json
{
    "timestamp": "2026-08-28T11:03:38Z",
    "watching_paths": null
}[root@rbmc (1:active)] ~ #
[root@rbmc-prototype (1:active)] ~ # datasynctool -w
No paths are currently being watched
[root@rbmc (1:active)] ~ #
```

Change-Id: I266865649e4608a047324a7c3ee2c397401c38a7
Signed-off-by: Arya K Padman <aryakpadman@gmail.com>